name: Linux Build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
    branches:
      - dev

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  extract-version:
    name: extract-version
    runs-on: ubuntu-latest
    outputs:
      espanso_version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: "Extract version"
        id: "version"
        run: |
          ESPANSO_VERSION=$(grep '^version' espanso/Cargo.toml | awk -F '"' '{ print $2 }')
          echo version: $ESPANSO_VERSION
          echo "::set-output name=version::v$ESPANSO_VERSION"

  linux-x11:
    needs: ["extract-version"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Print target version
        run: |
          echo Using version ${{ needs.extract-version.outputs.espanso_version }}
      - name: Build docker image
        run: |
          sudo docker build -t espanso-ubuntu . -f .github/scripts/Dockerfile
      - name: Build AppImage
        run: |
          sudo docker run --rm -v "$(pwd):/shared" espanso-ubuntu espanso/.github/scripts/ubuntu/build_appimage.sh
      - uses: actions/upload-artifact@v4
        name: "Upload artifacts"
        with:
          name: Linux X11 Artifacts
          path: |
            Espanso-X11.AppImage
            Espanso-X11.AppImage.sha256.txt
  
  linux-deb:
    needs: ["extract-version"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Print target version
        run: |
          echo Using version ${{ needs.extract-version.outputs.espanso_version }}
      - name: Build docker image
        run: |
          sudo docker build -t espanso-ubuntu . -f .github/scripts/Dockerfile
      - name: Build Deb packages
        run: |
          sudo docker run --rm -v "$(pwd):/shared" espanso-ubuntu espanso/.github/scripts/ubuntu/build_deb.sh
      - uses: actions/upload-artifact@v4
        name: "Upload artifacts"
        with:
          name: Ubuntu-Debian Artifacts
          path: |
            espanso-debian-x11-amd64.deb
            espanso-debian-wayland-amd64.deb
